accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.sign_out, name='logout'),
    path('punch/<clock_type>', views.punch, name='punch'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Clock(models.Model):

    CLOCK_TYPE = (
        ('0', '上班'),
        ('1', '下班')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    clock_type = models.CharField(choices=CLOCK_TYPE, max_length=2)  # 上班or下班
    clock_time = models.DateTimeField(default=timezone.now)

accounts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        label='帳號',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    password = forms.CharField(
        label='密碼',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib.auth.models import User


@login_required(login_url='/login')
def index(request):  # 首頁
    return render(request, 'accounts/index.html')


def sign_in(request):  # 登入頁

    if request.user.is_authenticated:
        return redirect('/')

    form = LoginForm()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('/')

    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


def sign_out(request):
    logout(request)
    return redirect('/login')


class LoginView(View):
    form_class = LoginForm
    template_name = 'accounts/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')

        form = self.form_class()
        return render(request, self.template_name, {'form': form, 'error_text': ''})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        username = form.data['username']
        password = form.data['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('/')
        else:
            return render(request, self.template_name, {'form': form, 'error_text': '帳號或密碼錯誤'})


def punch(request, clock_type):  # 打卡
    user = User.objects.get(username=request.user)
    clock = user.clock_set.create(clock_type=clock_type)
    clock.save()

    return redirect('/')

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block content %}

<p>Hello {{ user }}</p>
<a href="{% url 'accounts:punch' 0 %}"><button class="btn btn-primary">上班打卡</button></a>
<a href="{% url 'accounts:punch' 1 %}"><button class="btn btn-primary">下班打卡</button></a>
<a href="{% url 'accounts:logout' %}"><button class="btn btn-primary">登出</button></a>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="align-items-center">
        <form action="" method="post">
            {% csrf_token %}

            {{ form }}

            {% if error_text %}
            <p style="color: red">{{ error_text }}</p>
            {% endif %}
            <input type="submit" value="登入" class="btn btn-primary">
        </form>
    </div>
</div>

{% endblock %}